### ISSUE TITLE
Process animated gifs?

### ISSUE THREAD

**Issue by Cobertos** [geeogi/nuxt-responsive-loader#11]
I noticed this loader [isn't responsible for `.gif`s](https://github.com/geeogi/nuxt-responsive-loader/blob/master/lib/module.js#L41) and isn't processing my normal or animated gifs.

Is there any reason for this? Is it a feature that could be added or is this more dependent on the feature set of [`responsive-loader`](https://github.com/herrstucki/responsive-loader)?

**Comment by geeogi** [comment]
@Cobertos yes, responsive-loader doesn't support GIFs last time I tried. So this module doesn't target `.gif` files. 

You could add a custom rule in the webpack config that targets `.gif` files and uses a compression tool like https://www.npmjs.com/package/imagemin-giflossy to process them. That should be compatible with this module.

**Comment by Cobertos** [comment]
Thanks for the tip, I'll give it a try
