### ISSUE TITLE
Is There A Way To Make This Compatible With Gifs?

### ISSUE THREAD

**Issue by jgierlach** [geeogi/nuxt-responsive-loader#17]
This module has really increased the performance of my Nuxt app so thank you very much! I am getting an error when I try to load a gif file from the /uploads folder.

Module build failed (from ./node_modules/responsive-loader/lib/index.js):
Error: No mime type for file with extension gifsupported

I am using Nuxt version 2.12.2.

Is there something I could add or change in the modules configuration that would allow it to be compatible with .gif file?

**Comment by geeogi** [comment]
Hey, thanks for the detailed issue. This module should preserve the default handling for gif and svg files in any Nuxt project. So you should be able to add gifs to your app by following the usual [guide](https://nuxtjs.org/guide/assets/) i.e. adding your gifs in `/assets` and using `<img src="~/assets/image.gif">` in your template. Let me know if this doesn't work for you.
