### ISSUE TITLE
is there a way to use this with og:image

### ISSUE THREAD

**Issue by jessequinn** [geeogi/nuxt-responsive-loader#19]
I am struggling to figure out how we could use this in the head() of a vue page to populate the og:image with a image using this package. Any ideas?

**Comment by geeogi** [comment]
so long as you reference your image using `require('~/assets/image-name.jpg')` then webpack should inject the URL of the image generated by this module – did you try that?

**Comment by jessequinn** [comment]
thanks, i had tried this originally and it hadn't worked. Anyhow it does now. thanks
