### ISSUE TITLE
responsiveLoader options are ignored and break the module

### ISSUE THREAD

**Issue by chasebank** [geeogi/nuxt-responsive-loader#5]
This works awesome by default, just what I'm looking for, so thanks for sharing your work! But I haven't been able to set/change the default options.

For example, shouldn't this work?: 
```
responsiveLoader: {
    steps: 3,
    placeholder: false,
    quality: 75
  },
```

Here's a CodeSandbox: https://codesandbox.io/s/codesandbox-nuxt-responsive-loader-0o75o

Only the original image is processed. Commenting out the responsiveLoader object form the nuxt config returns the module to working order.

**Comment by geeogi** [comment]
Hi there, glad to hear you're enjoying the module 👍 

I _think_ you're missing the `min` and `max` props which are required for `steps` to take effect in the responsiveLoader config. You'll need something like this: 

```
responsiveLoader: {
    min: 100,
    max: 1000,
    steps: 3,
    placeholder: false,
    quality: 75
  },
```

Here's a sandbox which demonstrates custom config of this module: https://codesandbox.io/s/codesandbox-nuxt-responsive-loader-w3xg9?fontsize=14

Here's the available responsiveLoader options: https://github.com/herrstucki/responsive-loader#options

Let me know if that solves your problem!

**Comment by chasebank** [comment]
Hey @geeogi  thanks so much for the reply.

That does indeed fix the issue! However it also looks like min/max is required with any settings, regardless of setting steps? Just changing quality for example.

ie:
```
responsiveLoader: {
    quality: 75
  },
```
Which is fine enough, I'll just include the other settings to keep it working. Just curious if that's the expected behavior?

**Comment by geeogi** [comment]
Alternatively, you can specify a single `size` or `sizes` array 👍

The options that you pass to this module will be passed directly to the responsive-loader module, so the same configuration requirements will apply.

**Comment by chasebank** [comment]
Cool, thanks for the info! Everything's working great.
