### ISSUE TITLE
Exclude some file extensions?

### ISSUE THREAD

**Issue by YanDevDe** [geeogi/nuxt-responsive-loader#7]
Hello,
this modules work very good. But I'm currently having issue with ".svg" images. From https://github.com/herrstucki/responsive-loader, usually I can exclude .svg file by using "test" key. But for some reason, this module doesn't allow me to use test as option.

Maybe adding the "test" functionality would be good. 

Yan

**Comment by YanDevDe** [comment]
I just saw that you already included only those following images:
```
/\.(png|jpe?g|gif|webp)$/
```
But for some reason the svg are still returning as "undefined"

I'm using following method:

```
<img
    :src="require('~/assets/example.svg')"
/>
```

no matter what, if I use key "src", "placeholder" or nothing, it just return undefined. The .svg files works normal when I'm removing "nuxt-responsive-loader" from the modules at nuxt.config.js

**Comment by geeogi** [comment]
Hey, 

Thanks for raising this. 

Are you using any other Nuxt modules or custom webpack config to process `.svg` files? If so, can you [try placing that config _before_ nuxt-responsive-loader](https://github.com/geeogi/nuxt-responsive-loader#tips)?

**Comment by geeogi** [comment]
If that doesn't work, I think perhaps your suggestion for a PR is a good one: allow the developer to provide their own test string for the webpack config. I'm not sure that would that fix your issue though?

**Comment by YanDevDe** [comment]
@geeogi even if I just load only this nuxt module, I'm still have the issue to load svg from img with :src attribute. 
Temp solution which I had was to fork the project and I just removed any svg related from the code. Then it was working fine.

**Comment by YanDevDe** [comment]
But yeah, allowing user to create their own test string would be still good to have. 😄

**Comment by geeogi** [comment]
I think i've reproduced this bug. Will push a fix soon. For now, it's possible to use the Nuxt svg loader with this module: https://www.npmjs.com/package/nuxt-svg-loader

**Comment by aadgrant** [comment]
Thank you for a very good module but please can we have the option to exclude .gif as well as .svg (indeed just to define the test rule ourselves)?

**Comment by geeogi** [comment]
I have made some updates to this module which should resolve the above issues. This module is now enabled for PNG, JPG and WebP images. This module is not enabled for GIF and SVG images. 

So, with this module installed you can still use SVG images in your Nuxt projects as normal e.g. 

```
<img
    src='~/assets/example.svg'
/>
```

If you want more fine-grained configuration of the webpack loading rules then I recommend using a custom webpage configuration rather than this module (it will be simpler and safer for users to do this rather than passing a custom test to this module I think). Let me know if that solves your issue.

**Comment by geeogi** [comment]
hope the above message answers your queries @aadgrant @YanDevDe

**Comment by messismore** [comment]
I am getting the following error when I try to use `nuxt-responsive-loader` with `nuxt-svg-loader`:

`
ERROR Could not find the existing image loader rule. The webpack config has been edited, perhaps by another Nuxt module. To resolve this error try placing this module first in your Nuxt modules array or use a custom webpack configuration instead.
`

When placing `nuxt-responsive-loader` before `nuxt-svg-loader` in `nuxt.config.js` there is no error, but images do not load either.
Can you confirm nuxt-responsive-loader still works with nuxt-svg-loader @geeogi ?

**Comment by geeogi** [comment]
> I am getting the following error when I try to use `nuxt-responsive-loader` with `nuxt-svg-loader`:
> 
> `ERROR Could not find the existing image loader rule. The webpack config has been edited, perhaps by another Nuxt module. To resolve this error try placing this module first in your Nuxt modules array or use a custom webpack configuration instead.`
> 
> When placing `nuxt-responsive-loader` before `nuxt-svg-loader` in `nuxt.config.js` there is no error, but images do not load either.
> Can you confirm nuxt-responsive-loader still works with nuxt-svg-loader @geeogi ?

Hey — this module is no longer compatible with nuxt-svg-loader. The nuxt-svg-loader module modifies the web pack image rule in such a way that breaks this module and makes it difficult for other image modules like this to work around.  

This module modifies the web pack image rule in such a way that should make it simple for other modules (like nuxt-svg-loader) to work with. Wouldn’t be hard to raise a PR on their end to make the two compatible. Sorry I haven’t had a chance to do this myself yet. 

Alternatively, you could use a custom web pack config instead.

**Comment by messismore** [comment]
Ah okay thank you! I'll try and see if I can make it work.
