### ISSUE TITLE
Question: Does It Work With a CDN/Headless CMS?

### ISSUE THREAD

**Issue by alivefromupstairs** [geeogi/nuxt-responsive-loader#8]
> Add your images to the `assets` directory

Sorry, I'm not on my coding machine to try for myself. So, I would like to know if I can load images during `nuxt generate` from a CDN or a headless CMS (using GraphQL for instance)?

**Comment by geeogi** [comment]
This module should work so long as the images exist in the `assets` folder when Webpack runs. Not sure if that fits your use case. 

Alternatively, if you're pulling in images during the generate step in a custom script, then you could use [responsive-loader](https://github.com/herrstucki/responsive-loader) inline. Alternatively, process the images on the CMS at the upload step. 

Would be interested to hear how you get on!

**Comment by alivefromupstairs** [comment]
The CMS I went with offered responsive images through URL manipulation. So, I created a Vue filter to help with those. But there are ways to get webpack to resolve http resources like [webpack-require-http](https://www.npmjs.com/package/webpack-require-http), [webpack-external-import](https://github.com/ScriptedAlchemy/webpack-external-import), or [script.js](https://github.com/ded/script.js/). I did not try them, but I'll try to get this to work on the next project.
