### ISSUE TITLE
Dynamic require() will not work

### ISSUE THREAD

**Issue by MrSunshyne** [geeogi/nuxt-responsive-loader#9]
Hi ! 

Thanks for the awesome module !

When trying to use it in a 'card' that will know the path of the image at compile time(npm run generate), 
where the data coming from a headless cms, I need to structure my code as such : 

```js
export default {
     data() {
       return { 
          imageUrl: '~/assets/images/photo.jpg'
       }
     }
}
```

```html
    <img
      :src="require(imageUrl).placeholder"
    />
```

Unfortunately that doesn't work because [require doesn't like variables](https://github.com/webpack/webpack-dev-server/issues/212), it want's a string as parameter. and I end up with this error : 

```
Cannot find module '~/assets/images/photo.jpg'

 ```
This works : 

```html
    <img
      :src="require('~/assets/images/photo.jpg').placeholder"
    />
```

Is there a way to make this work ? 

I thought of not using `require(xx).placeholder` and hardcoding the paths myself, 
i.e. something like `imageUrl + '-w-200'` but I can't figure out how to remove the `hash` from the filename so that I can make it predictable.

Any tips much much appreciated !

**Comment by geeogi** [comment]
It's possible to configure the name of the processed image files like so:

```
// file: nuxt.config.js

export default {
  // ...
  // Specify your options as a responsiveLoader object
  responsiveLoader: {
    name: 'img/[hash:7]-[width].[ext]',
    quality: 65 // choose a lower value if you want to reduce filesize further
    // e.t.c.
  }
}
```

The hash should be invariant and predictable. Does that help?

**Comment by MrSunshyne** [comment]
@geeogi, the hash in this case wouldn't be predictable as I wouldn't know how to get the hash. Unless there's something i missed?

Using the 'name' to manually rewrite the srcset would be a workaround to be honest and a last resort solution.

Do you think there's any way to use the original solution with with a dynamic argument/variable or maybe not use `require` at all?

My use case is as follows : 
I have a blog listing page and I need to show the image inside a picture tag when i'm running nuxt generate.

**Comment by geeogi** [comment]
@MrSunshyne Here's an example where I'm using string interpolation to dynamically import an image by a fileName variable: https://github.com/carole-hector/site/blob/9e7e5fdf7ffe952f048b6171740cf5167e757c7a/components/v-image.vue#L27

This project uses this module (nuxt-responsive-loader) and `nuxt generate` so it should hopefully fit your use case.
